// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnakQEibUmvwOoc01iuDFazqp4bJL6L0E',
    appId: '1:578883270908:web:1277de56cd9bacdb6e3f79',
    messagingSenderId: '578883270908',
    projectId: 'shivankarvid',
    authDomain: 'shivankarvid.firebaseapp.com',
    databaseURL: 'https://shivankarvid-default-rtdb.firebaseio.com',
    storageBucket: 'shivankarvid.appspot.com',
    measurementId: 'G-QSYR54CGBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY3i-eo6uSj1vMaBuaudMyOkW3qfpQAG8',
    appId: '1:578883270908:android:5b356f199bf5d1c76e3f79',
    messagingSenderId: '578883270908',
    projectId: 'shivankarvid',
    databaseURL: 'https://shivankarvid-default-rtdb.firebaseio.com',
    storageBucket: 'shivankarvid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW_oHfnk7AwSgVSsLfYuCh5OGNqsUqrdg',
    appId: '1:578883270908:ios:4b1ee84e7d7c04086e3f79',
    messagingSenderId: '578883270908',
    projectId: 'shivankarvid',
    databaseURL: 'https://shivankarvid-default-rtdb.firebaseio.com',
    storageBucket: 'shivankarvid.appspot.com',
    androidClientId: '578883270908-js9fft7g9kjqpq906hqari1g576kgll4.apps.googleusercontent.com',
    iosClientId: '578883270908-lidtndp2kss051bhmuroea8amcccnili.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW_oHfnk7AwSgVSsLfYuCh5OGNqsUqrdg',
    appId: '1:578883270908:ios:4b1ee84e7d7c04086e3f79',
    messagingSenderId: '578883270908',
    projectId: 'shivankarvid',
    databaseURL: 'https://shivankarvid-default-rtdb.firebaseio.com',
    storageBucket: 'shivankarvid.appspot.com',
    androidClientId: '578883270908-js9fft7g9kjqpq906hqari1g576kgll4.apps.googleusercontent.com',
    iosClientId: '578883270908-lidtndp2kss051bhmuroea8amcccnili.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminApp',
  );
}
